{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-db-host/versions/latest" 
        fileName: "database-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-cloud-native-extraction-db-user/versions/latest" 
        fileName: "cloud-native-extraction-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-cloud-native-extraction-db-password/versions/latest" 
        fileName: "cloud-native-extraction-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-cloud-native-extraction-db/versions/latest" 
        fileName: "cloud-native-extraction-db"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_cloud_native_extraction_migrator.secretName }}
      type: Opaque
      data:
      - objectName: "database-host"
        key: database-host
      - objectName: "cloud-native-extraction-db-user"
        key: user
      - objectName: "cloud-native-extraction-db-password"
        key: password
      - objectName: "cloud-native-extraction-db"
        key: database-db
{{- end }}
